# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
- job: job1
  pool:
    name: Agent Devops test    # your job runs on an agent in this pool
    demands: Agent.name -equals DCTEST8976   # the agent must have this capability to run the job
  steps:
  - script: echo hello world

- job: job2
  pool:
    name: Agent Devops test    # your job runs on an agent in this pool
    demands: Agent.name -equals DCTEST8976-2    # the agent must have this capability to run the job
  steps:
  - script: echo hello world
